### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by iitjee** [sergiokas/Extensity#55] opened 2020-02-12 09:35 UTC
I do touch typing a lot and, therefore hate to use a mouse. 

AFter I trigger extensify and type the name of an extension, I'll have to use a mouse to click one among the search results. Is it possible to navigate through the results via keyboard itself? I tried tabbing but that didn't help.

**Comment by DummybugStudios** [comment] 2020-03-29 06:27
This is the same as issue #47 that I opened ages ago :)

**Comment by sergiokas** [comment] 2020-09-02 19:42
Duplicate of #47

**Closed by sergiokas** 2020-09-02 19:42 UTC
