### ISSUE TITLE
Sync profile between Browser

### ISSUE THREAD

**Issue by florentulve** [sergiokas/Extensity#10] opened 2016-10-10 09:56 UTC
Hi,
First, good extension, great work !

I think it would be great if extensify could sync profiles settings between browser. 
By replacing localStorage with [chrome.storage.sync](https://developer.chrome.com/extensions/storage) api I think it could be done without too much effort.

**Comment by sergiokas** [comment] 2017-03-01 21:49
duplicate of #9

**Closed by sergiokas** 2017-03-01 21:49 UTC
